---
permalink: rhel-install/task-replace-the-default-workflow-automation-ssl-certificate-linux.html 
sidebar: sidebar 
keywords: replace, default, workflow, automation, ssl, certificate 
summary: 如果证书已过期或要延长证书的有效期，则可以替换默认的 Workflow Automation （ WFA ） SSL 证书。 
---
= 替换默认的 Workflow Automation SSL 证书
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果证书已过期或要延长证书的有效期，则可以替换默认的 Workflow Automation （ WFA ） SSL 证书。

您必须对安装了 WFA 的 Linux 系统具有 root 权限。

此操作步骤 将使用默认 WFA 安装路径。如果您在安装期间更改了默认位置，则必须使用自定义 WFA 安装路径。

.步骤
. 以 root 用户身份登录到 WFA 主机。
. 在 Shell 提示符处，导航到 WFA 服务器上的以下目录： wfa_install_location/wfa/bin
. 停止 WFA 数据库和服务器服务：
+
` 。 /WFA -stop=WFA`

+
` 。 /WFA -stop=DB`

. 从以下位置删除 WFA.keystore 文件： wfa_install_location/wfa/jboss/standalone / configuration/keystore 。
. 在 WFA 服务器上打开 Shell 提示符，然后将目录更改为以下位置： <OpenJDK_INSTALL_location>/bin
. 获取数据库密钥：
+
`keytool -keysize 2048 -genkey -alias "ssl keystore" -keyalg rsa -keystore "WFA_install_location/wfa/jboss/standalon/configuration/keystore/wfa.keystore" -validity xxxx`

+
xxxx 是新证书有效期的天数。

. 出现提示时，请提供密码（默认密码或新密码）。
+
默认密码是随机生成的加密密码。

+
要获取默认密码并对其进行解密、请按照知识库文章中的步骤进行操作 link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F["如何在WFA 5.1.0.4上续订自签名证书"^]

. 输入证书的所需详细信息。
. 查看显示的信息，然后输入 `是` 。
. 出现以下消息时按 * Enter * ： Enter key password for <SSL keystorage> <return if same as keystore password> 。
. 重新启动 WFA 服务：
+
` 。 /WFA -start=DB`

+
` 。 /WFA -start=WFA`


