---
permalink: rhel-install/task-configure-authentication-settings.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, configure, authentication, settings 
summary: 您可以将 OnCommand Workflow Automation （ WFA ）配置为使用 Microsoft Active Directory （ AD ）轻型目录访问协议（ LDAP ）服务器进行身份验证和授权。 
---
= 配置身份验证设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将 OnCommand Workflow Automation （ WFA ）配置为使用 Microsoft Active Directory （ AD ）轻型目录访问协议（ LDAP ）服务器进行身份验证和授权。

您必须已在环境中配置 Microsoft AD LDAP 服务器。

WFA 仅支持 Microsoft AD LDAP 身份验证。您不能使用任何其他 LDAP 身份验证方法，包括 Microsoft AD 轻型目录服务（ AD LDS ）或 Microsoft 全局目录。


NOTE: 在通信期间， LDAP 会以纯文本格式发送用户名和密码。但是， LDAPS （ LDAP 安全）通信已加密且安全。

.步骤
. 以管理员身份通过 Web 浏览器登录到 WFA 。
. 向所需角色添加 Active Directory 组名称列表。
+

NOTE: 您可以在 Active Directory 组窗口中为所需角色添加 AD 组名称列表。

+
xref:task-add-active-directory-group-names.adoc[Active Directory 组窗口]

. 单击 * 管理 * > * WFA 配置 * 。
. 在 WFA 配置对话框中，单击 * 身份验证 * 选项卡，然后选中 * 启用 Active Directory* 复选框。
. 在以下字段中输入所需信息：
+
.. 如果要对域用户使用用户@域格式，请在 * 用户名属性 * 字段中将 sAMAccountName 替换为 userPrincipalName 。
.. 如果您的环境需要唯一值，请编辑所需字段。


. 单击 * 添加 * 以在 Active Directory 服务器表中添加采用以下 URI 格式的 Active Directory ： `ldap ： //active_directory_server_address\[ ： port\]`
+
LDAP ： //NB-T01.example.com[:389]

+
如果已启用基于 SSL 的 LDAP ，则可以使用以下 URI 格式： `ldaps ： //active_directory_server_address\[ ： port\]`

. 提供用于绑定 LDAP 服务器和基础 DN 的凭据。
. 测试给定用户的身份验证：
+
.. 输入用户名和密码。
.. 单击 * 测试身份验证 * 。


+

NOTE: 您必须已添加 Active Directory 组以测试 WFA 中给定用户的身份验证。

. 单击 * 保存 * 。

