---
settings:
  name: OnCommand Workflow Automation 5.1
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: OnCommand Workflow Automation 5.1 文档
    url: "/index.html"
  - title: 发行说明
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: workflow
  - section: help
  - title: 法律声明
    url: "/reference-legal-notices.html"
