---
settings:
  name: OnCommand Workflow Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: OnCommand Workflow Automation文档
    url: "/index.html"
  - title: 发行说明
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: workflow
  - section: help
  - title: 法律声明
    url: "/reference-legal-notices.html"
