---
permalink: help/reference-new-command-definition-dialog-box.html 
sidebar: sidebar 
keywords: new, command, definition, dialog box, enable, define, create, workflow, predefined, meet, requirements 
summary: '通过 " 新建命令定义 " 对话框，您可以定义新命令。如果预定义的命令不符合您的要求，您可以为工作流创建新命令。' 
---
= 新建命令定义对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 " 新建命令定义 " 对话框，您可以定义新命令。如果预定义的命令不符合您的要求，您可以为工作流创建新命令。

* 属性选项卡
* 代码选项卡
* 参数定义选项卡
* 参数映射选项卡
* 预留选项卡
* 验证选项卡




== 属性选项卡

用于指定命令的属性，例如名称，问题描述 和实体版本。

* * 名称 *
+
用于指定命令的名称。要保存此命令，必须指定一个名称。

* * 实体版本 *
+
用于以 `major.minor.revision` format 指定命令的版本号，例如 1.0.0 。

* * 问题描述 *
+
用于输入命令的问题描述 。

* * 字符串表示 *
+
用于使用 MVFLEX 表达式语言（ MVEL ）语法为命令指定字符串表示形式。

+
要保存命令，必须指定字符串表示形式。字符串表示用于在规划和执行期间在工作流设计中显示命令的详细信息。您只能使用命令的字符串表示形式参数表示该命令。

* * 超时（秒） *
+
用于指定命令的超时值（以秒为单位）。默认值为 600 秒。

* * 命令类型 *
+
用于指定命令的执行类型。

+
** * 标准执行 *
+
允许在不等待任何时间的情况下执行命令。默认情况下会选择标准执行。

** * 等待条件 *
+
用于指定执行命令前必须等待的时间（以秒为单位）。默认值为 60 秒。



* * 最低软件版本 *
+
指定运行命令所需的最低软件版本。例如，该软件可以是集群模式 Data ONTAP 8.2.0 和 vCenter 6.0 。版本以逗号分隔的值显示。





== 代码选项卡

用于以选定脚本语言输入命令的代码。您可以通过从脚本语言下拉列表中选择所需语言来添加新的脚本语言。

* * 发现参数 *
+
将 PowerShell 代码中定义的参数复制到 " 参数定义 " 表和 " 参数映射 " 表。





== 参数定义选项卡

显示在代码选项卡中输入的代码中定义的参数。

* * 名称 *
+
显示参数的名称。

* * 问题描述 *
+
显示参数的问题描述 。

* * 必填 *
+
显示选定的必填参数复选框。

* * 类型 *
+
显示参数的类型，例如字符串，枚举，数组或密码。

* * 值 *
+
显示为参数设置的值。

* * 添加参数 *
+
用于在选定脚本语言为 Perl 时向命令添加参数。

* * 删除参数 *
+
用于在选定脚本语言为 Perl 时从命令中删除参数。





== 参数映射选项卡

用于将参数映射到词典对象以及指定属性和对象名称。

* * 名称 *
+
显示参数的名称。

* * 类型 *
+
用于为参数选择词典对象。

* * 属性 *
+
用于指定所需属性。您可以选择属性（如果可用），也可以输入属性。

* * 对象名称 *
+
用于指定词典对象的名称。





== 预留选项卡

用于预留命令所需的资源。

* * 预留脚本 *
+
用于输入 SQL 查询以预留命令所需的资源。这有助于确保资源在计划的工作流执行期间可用。

* * 预留表示 *
+
用于使用 MVEL 语法为预留指定字符串表示形式。字符串表示用于在预留窗口中显示预留的详细信息。





== 验证选项卡

用于在执行命令后验证预留并删除预留。

* * 验证脚本 *
+
用于输入 SQL 查询以验证预留脚本预留的资源的使用情况。验证脚本还会验证 WFA 缓存是否已更新，并在缓存采集后删除预留。

* * 测试验证 *
+
打开验证对话框，在此可以测试验证脚本的参数。





== 命令按钮

* * 测试 *
+
打开 <ScriptLanguage > 中的 Testing Command <CommandName> 对话框，在此可以测试此命令。

* * 保存 *
+
保存命令并关闭对话框。

* * 取消 *
+
取消所做的更改（如果有），然后关闭对话框。


