---
permalink: help/reference-edit-workflow-window.html 
sidebar: sidebar 
keywords: workflow, window, display, select, associated, commands, parameters, blue boxes, columns, arranged, sequential, order, execution, left, right, variables, objects, gray boxes 
summary: Workflow < 工作流名称 > 窗口显示选定工作流及其关联的命令和参数。与此工作流关联的命令将在按从左到右顺序排列的列中显示为蓝色框。每个命令的变量和对象在命令下方显示为灰色框。 
---
= Workflow <Workflow name> 窗口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Workflow < 工作流名称 > 窗口显示选定工作流及其关联的命令和参数。与此工作流关联的命令将在按执行顺序从左到右排列的列中显示为蓝色框。每个命令的变量和对象在命令下方显示为灰色框。



== 工作流选项卡

通过工作流选项卡，您可以选择和使用子工作流和命令，并自定义显示名称。

* * 可用步骤 *
+
提供可添加到工作流中的子工作流和命令列表。

+
您可以在文本框中使用名称，方案和最低软件版本作为搜索字符串来搜索子工作流或命令。

+
您可以通过重新排列命令的顺序来自定义工作流显示。要重新排列命令，您可以按所需顺序拖放命令。双击某个命令会将该命令移至列表末尾。您可以通过在蓝色框中双击命令的显示名称来修改显示名称。您可以删除命令，方法是将光标移动到蓝色框上，然后单击右上角的 "`X` " 。

+
您可以单击行号对行执行各种功能。

+
** * 插入行 *
+
在工作流中的选定行上方或下方插入新行。

** * 复制行 *
+
从工作流复制选定行并将其保存到剪贴板。复制行时，将复制为此行设置的重复详细信息。

** * 重复行 *
+
打开行重复详细信息对话框，在此可以指定重复类型。

** * 添加条件 *
+
打开行 < 行号 > 的条件对话框，在此可以选择一个条件。选定条件适用于行中的所有命令。只有在满足选定条件时，才会执行此行中的所有命令。

** * 删除行 *
+
从工作流中删除选定行。



* * 粘贴行 *
+
将复制的行粘贴到选定行上方或下方。选择复制行功能后，此选项可用。





== 详细信息选项卡

" 详细信息 " 选项卡可用于提供有关工作流的常规信息。

* * 工作流名称 *
+
用于使用字母数字字符串指定工作流的名称。

* * 实体版本 *
+
用于输入 `major.minor.revision` 格式的工作流版本号，例如 1.0.0 。

* * 类别 *
+
显示工作流的关联类别。您可以从 " 类别 " 窗口将工作流分配给某个类别。

* * 工作流问题描述
+
用于输入工作流的问题描述 。您可以单击字段以打开编辑问题描述 对话框。

* * 可投入生产 *
+
用于将工作流标记为已准备好投入生产，从而可以执行此工作流并将其列在工作流窗口中。

* * 考虑保留要素 *
+
用于在选定资源可用于工作流时对工作流使用预留功能，直到您配置的预留到期期限为止。通过预留功能，您可以在选择资源期间排除其他工作流预留的资源。

+

NOTE: 如果您需要筛选器仅搜索永久性缓存的内容而不考虑其他工作流设置的预留，则不能选中此复选框。

* * 启用元素存在验证 *
+
用于验证是否存在元素，并避免在执行工作流期间某些操作失败。例如，您可以避免在与现有卷名称相同的阵列中创建新卷。

* * 最低软件版本 *
+
指定执行工作流所需的最低软件版本。例如，该软件可以是集群模式 Data ONTAP 8.2.0 和 vCenter 6.0 。版本以逗号分隔的值显示。





== 用户输入选项卡

通过用户输入选项卡，您可以查看和编辑在定义工作流对象和创建用户输入时创建的用户输入属性。预览或执行工作流时，系统会填充用户输入属性的值。

您可以双击要编辑的用户输入，此时将打开编辑变量： <user_input> 对话框，以便编辑用户输入。

您可以通过重新排列列顺序来自定义表显示。要重新排列列，您可以按所需顺序拖放列。但是，您不能隐藏或删除其中任何列。

* * 名称 *
+
显示用户输入属性的名称。

* * 显示名称 *
+
显示向工作流用户显示的名称。

* * 类型 *
+
显示用户输入类型，例如字符串，查询，布尔值，表， 或密码。

* * 值 *
+
显示用户输入允许的值，例如数字范围和字符串正则表达式。

* * 默认值 *
+
显示用户输入的默认值。

* * 输入依赖关系 *
+
显示列表中为选定用户输入提供值的另一个用户输入。

* * 组 *
+
显示用户输入属性的组名称。

* * 必填 *
+
显示用户输入的状态。如果此复选框显示为选中，则执行工作流时必须具有用户输入属性。

* * 命令按钮 *
+
** * 启动 *
+
将选定条目在表中上移一行。

** * 关闭 *
+
将选定条目在表中下移一行。







== 常量选项卡

通过常量选项卡，您可以定义可在工作流中多次使用的常量值。您可以指定以下值作为常量值：

* 数字
* 字符串
* MVEL 表达式
* 功能
* 用户输入
* 变量


您可以通过对每列进行排序以及重新排列列顺序来自定义表显示。

* * 名称 *
+
显示常量的名称。

* * 问题描述 *
+
用于为常量指定问题描述 。

* * 值 *
+
用于指定常量的值。

* * 命令按钮 *
+
** * 添加 * 。
+
在常量表中添加新行。

** * 删除 *
+
从常量表中删除选定行。



+
您也可以右键单击这些常量以使用复制和粘贴功能。





== 返回参数选项卡

通过返回参数选项卡，您可以为工作流定义并提供返回参数的问题描述 ，这些参数可以从监控窗口或 Web 服务查看。

* * 参数值 *
+
用于指定参数值。

* * 参数名称 *
+
用于指定参数名称。

* * 问题描述 *
+
用于为选定参数指定问题描述 。

* * 命令按钮 *
+
** * 添加行 *
+
在 "Return Parameters" 表中添加新行。

** * 删除行 *
+
从 "Return Parameters" 表中删除选定行。







== 帮助内容选项卡

通过帮助内容选项卡，您可以添加，查看和删除工作流的帮助内容。工作流帮助内容提供了有关存储操作员工作流的信息。



== 高级选项卡

通过高级选项卡，您可以配置自定义 URI 路径，以便通过 API 调用执行工作流。URI 路径中的每个分段可以是一个字符串，也可以是用户在工作流中输入的有效名称（括号中）。

例如， /DevOps/\ ｛ ProjectName ｝ /clone 。此工作流可以调用 _https ： //WFA-Server ： HTTPS_port/rest/DevOps/Project1/clone/Jobs 。



== 命令按钮

命令按钮位于工作流窗口的底部。也可以从窗口中的右键单击菜单访问这些命令。

* * 预览 *
+
打开预览工作流对话框，在此可以指定用户输入属性。

* * 另存为 *
+
用于使用新名称保存工作流。

* * 保存 *
+
保存配置设置。


