---
permalink: help/reference-edit-variable-dialog-box.html 
sidebar: sidebar 
keywords: edit, variable, dialog box, enable, user, input, attributes, workflow 
summary: 通过编辑变量： <UserInputName> 对话框，您可以编辑工作流的用户输入属性。 
---
= 编辑变量对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过编辑变量： <UserInputName> 对话框，您可以编辑工作流的用户输入属性。



== 属性

* * 变量名称 *
+
用于编辑用户输入的名称。重命名用户输入将更新工作流中对用户输入的所有引用。

* * 显示名称 *
+
用于指定或编辑用户输入的显示名称。如果您创建了名称相似的用户输入属性，则可以指定唯一的显示名称。

* * 问题描述 *
+
用于指定或编辑用户输入的问题描述 。执行或预览工作流时，问题描述 会显示为工具提示。

* * 类型 *
+
用于选择用户输入的类型。此时将根据选定选项显示字段或指向对话框的链接。可用选项包括：

+
** 字符串：用于在 "RegEx" 字段中为有效值输入正则表达式，例如 A* 。
** number ：用于在范围字段中输入数字范围，例如 1 到 15 。
** 枚举：用于在枚举值字段中输入闭合值列表。
** query ：用于输入简单的 SQL 查询以获取结果。
+
用户只能从结果的第一列中选择值。

** 查询（多选）：用于输入获取值列表的 SQL 查询。
+
用户可以在执行工作流时选择一个值或多个值，例如，您可以选择一个卷，多个卷或包含其共享和导出的卷。

+
您可以从结果中显示的任何列中选择值。选择一行可从选定行的所有列中选择值。

** 布尔值：用于在用户输入对话框中显示复选框。
** 表：用于指定表的列标题，可用于在执行工作流期间输入多个值，例如，可用于指定节点名称和端口名称列表的表。
+
您还可以配置列用户输入的类型以及与列用户输入关联的属性。此时将根据选定用户输入类型显示一个对话框。可用选项包括：

+
*** 字符串：用于在 "RegEx" 字段中为有效值输入正则表达式，例如 A* 。
*** number ：用于在范围字段中输入数字范围，例如 1 到 15 。
*** 枚举：用于在枚举值字段中输入闭合值列表。
*** query ：用于输入简单的 SQL 查询以获取结果。
+
用户只能从结果的第一列中选择值。表用户输入所在列中的查询不能引用查询中的其他用户输入。

*** Boolean ：用于从下拉列表中选择 "`true` " 或 "`false` " 作为布尔值。


** Password ：用于对用户输入的密码进行加密。
+
加密后，密码将在 WFA 应用程序和日志文件中显示为一系列星号字符。

** 词典：用于为选定词典条目添加表数据。
+
词典条目属性用于选择要返回的属性。您可以在执行工作流时选择一个或多个值。例如，您可以选择一个卷，多个卷或具有其共享和导出的卷。默认情况下，系统会选择单个值。您也可以选择要筛选的规则。规则由词典条目属性，运算符和值组成。此属性还可以包括其引用的属性。例如，您可以通过列出名称以字符串 "`aggr` " 开头且可用大小大于 5 GB 的所有聚合来为聚合指定规则。该组中的第一个规则是属性 `name` ，操作符为 `start-with` ，值为 kaggr 。同一组的第二条规则是属性 `available_size_mb` ，其中运算符为 ` >` ，值为 5000 。



* * 锁定值 *
+
用于指定是否允许用户输入查询返回的值以外的值。选中此复选框不允许用户提供值；只能选择查询返回的值。此选项与 Enum 和 Query 类型选项结合使用。

* * 默认值 *
+
用于设置用户输入的默认值。

* * 必填 *
+
用于指定执行工作流时是否需要用户输入。





== 组

* * 组名称 *
+
用于将相关用户输入属性分组在一起。用户输入属性将显示在您在预览或执行工作流时定义的组中。例如，您可以将与卷详细信息相关的用户输入属性分组在一起。

* * 默认扩展组 *
+
用于将组中指定的所有用户输入属性显示为扩展列表。如果未选中此复选框，则用户输入组将显示为折叠。





== 依赖关系

用于根据为其他用户输入输入的值启用用户输入。例如，在配置 NAS 协议的工作流中，您可以将协议所需的用户输入指定为 "`NFS` " 以启用 " `read-write host lists` " 用户输入，或 "`cifs` " 以启用 "`CIFS ACL 配置` " 。

* * 选择要依赖的用户输入 *
+
用于选择启用 "Variable Name" 字段中显示的用户输入所需的用户输入。

* * 适用值（逗号分隔） *
+
用于指定条件用户输入的值，以启用 " 变量名称 " 字段中显示的用户输入。


