---
permalink: help/reference-resource-selection-dialog-box.html 
sidebar: sidebar 
keywords: resource, selection, dialog box, enable, search, map, command 
summary: 通过资源选择对话框，您可以搜索资源并将资源映射到命令。 
---
= 资源选择对话框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过资源选择对话框，您可以搜索资源并将资源映射到命令。

* 选择 < 词典对象 > 按选项卡
* 高级选项卡




== 选择 < 词典对象 > 按选项卡

通过此选项卡，您可以指定查找器或筛选器作为搜索条件，并输入选定搜索条件的属性。您也可以将选定筛选器另存为查找器。

* * 定义筛选规则 *
+
用于为词典条目资源（例如 vFiler 单元，聚合和虚拟机）定义一组规则。

+
筛选器规则可以包含一组或多组规则。

+
规则由词典条目属性，运算符和值组成。此属性还可以包括其引用的属性。例如，您可以按如下所示为聚合指定一个规则：列出名称以字符串 "`aggr` " 开头且可用大小大于 5 GB 的所有聚合。组中的第一个规则是属性 "`name` " ，运算符为 " `start-with` " ，值为 "`aggr` " 。同一组的第二条规则是属性 "`available_size_mb` " ，运算符为 "` >` " ，值为 "`5000` " 。

+
如果选择了查找器，则 * 定义筛选规则 * 选项将被禁用。

+
您可以通过单击 * 重置 * 按钮清除指定的值。

* * 按自然键选择一个资源 *
+
用于根据资源的自然密钥选择资源。

* * 查找器 *
+
用于从列表中选择查找器。默认情况下会选择 * 无 * 。

+
筛选器显示在查找器列表下方。如果选择了查找器，则无法选择筛选器。

* * 参数 *
+
用于输入选定查找器或筛选器的值。您必须输入所有必需值才能完成搜索条件。

* * 命令按钮 *
+
** * 另存为查找器 *
+
将选定筛选器保存为查找器。

** * 测试 *
+
用于在参数区域中指定值之前测试选定筛选器的参数。

** * 确定 *
+
保存配置设置并关闭对话框。

** * 取消 *
+
取消所做的更改（如果有），然后关闭对话框。







== 高级选项卡

通过此选项卡，您可以指定何时执行搜索，并对资源属性和资源属性状态进行排序。

* * 始终执行此搜索 *
+
执行命令时，执行搜索时不受任何限制。

* * 只有在以下表达式的计算结果为 true 时执行搜索 *
+
只有在框中指定的可选属性值为 "`true` " 时，才执行搜索。您可以使用 MVFLEX 表达式语言（ MVEL ）语法指定可选属性。

* * 排序表 *
+
显示在 * 选择 < 词典对象 > 方式 * 选项卡中选定筛选器的属性和排序顺序。排序顺序对于资源选择来说非常重要—例如，如果选择降序作为聚合的排序顺序，则会选择最大值为 `available_space` 的聚合作为资源。要更改属性的排序顺序，您可以单击属性的状态列，然后从列表中选择所需的排序顺序。

* * 命令按钮 *
+
** * 启动 *
+
将选定条目在排序表中上移一行。

** * 关闭 *
+
将选定条目在排序表中下移一行。




