---
permalink: workflows/concept-how-you-define-user-input.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, user, input, data, options, available, during, execution, define, parameters, enhance, flexibility, usability 
summary: OnCommand Workflow Automation （ WFA ）用户输入是在执行工作流期间可用的数据输入选项。您必须为工作流定义用户输入参数，以提高工作流的灵活性和可用性。 
---
= 如何定义用户输入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）用户输入是在执行工作流期间可用的数据输入选项。您必须为工作流定义用户输入参数，以提高工作流的灵活性和可用性。

用户输入将显示为输入字段，在预览或执行工作流时，可以使用相关数据填写这些字段。在工作流中指定命令详细信息时，您可以通过使用美元符号（ $ ）前缀标签或变量来创建用户输入字段。例如， $VolumeName 将创建卷名称用户输入字段。WFA 会自动使用您创建的用户输入标签在 Workflow <Workflow name> 窗口中的 User Inputs 选项卡中进行填充。此外，您还可以通过修改用户输入属性（例如类型，显示名称，默认值和验证值）来定义用户输入的类型并自定义输入字段。



== 用户输入类型选项

* * 字符串 *
+
您可以使用正则表达式表示有效值，例如 A* 。

+
`0d` 和 `0f` 等字符串将作为类似于 `0d` 的数字进行评估，并将其评估为双精度类型 0 。

* * 数字 *
+
您可以定义一个可以选择的数字范围，例如 1 到 15 。

* * 枚举 *
+
您可以创建枚举值，在使用枚举类型填充用户输入字段时可以选择这些值。您可以选择锁定已创建的枚举值，以确保仅为用户输入选择已创建的值。

* * 查询 *
+
如果要从 WFA 缓存中的可用值中选择用户输入，可以选择查询类型。例如，您可以使用以下查询自动使用 WFA 缓存中的 IP 地址和名称值填充用户输入字段： * `S选择 IP ，名称来自 storage.array 。` * 您可以选择锁定查询检索到的值，以便仅选择查询重试的结果。

* * 查询（多选） *
+
查询（多选）类型与查询类型类似，可在执行工作流期间选择多个值。例如，用户可以选择多个卷或一个卷及其共享和导出。您可以允许用户选择多行，也可以将选择限制为一行。选择一行可从选定行的所有列中选择值。



使用查询（多选）类型的用户输入时，可以使用以下功能：

* GetSize
* getValueAt
* getValueAt2D
* getValueFrom2DByrowKey
+
** * 布尔值 *
+
您可以使用布尔类型在用户输入对话框中显示复选框。对于可能值为 "`true` " 和 "`false` " 的用户输入，必须使用布尔类型。

** * 表 *
+
您可以使用用户输入的表类型指定表的列标题，以便在执行工作流期间输入多个值。例如，可用于指定节点名称和端口名称列表的表。您还可以为列标题指定以下用户输入类型之一，以验证运行期间输入的值：



* string
* 数字
* 枚举
* 布尔值
* query `String` 是列标题的默认用户输入类型。您必须双击类型列以指定其他用户输入类型。
+
您可以在设计器中打开创建 SnapMirror 策略和规则工作流，以查看在 `SnapMirrorPolicyRule` 用户输入中如何使用用户输入类型。

+
使用用户输入的表类型时，可以使用以下功能：

* GetSize
* getValueAt
* getValueAt2D
* getValueFrom2DByrowKey 您可以在设计器中打开 * 创建并配置带有无限卷的 Storage Virtual Machine * 工作流，以查看如何使用表类型。
+
** * 密码 *
+
您可以对用于输入密码的用户输入使用密码类型。用户输入的密码会进行加密，并在 WFA 应用程序和日志文件中显示为一系列星号字符。您可以使用以下功能对密码进行解密，然后命令可以使用该密码：



* 对于 Perl 命令： WFAUtil ： getWfaInputPassword （ $password ）
* 对于 PowerShell 命令： get-WfaInputPassword -EncryptedPassword $password
+
此处， $password 是 WFA 传递给命令的加密密码。

+
** * 词典 *
+
您可以为选定词典条目添加表数据。词典条目属性用于选择要返回的属性。您可以在执行工作流时选择一个或多个值。例如，您可以选择一个或多个卷。默认情况下，系统会选择单个值。您也可以选择要筛选的规则。规则由词典条目属性，运算符和值组成。此属性还可以包括其引用的属性。

+
例如，您可以通过列出名称以字符串 "`aggr` " 开头且可用大小大于 5 GB 的所有聚合来为聚合指定规则。组中的第一个规则是属性 `name` ，运算符 `start-with` 以及值 aggr 。同一组的第二条规则是属性 `available_size_mb` ，其中运算符为 ` >` ，值为 `5000 。`





下表列出了可应用于用户输入类型的选项：

[cols="2*"]
|===
| 选项 | Description 


 a| 
正在验证
 a| 
您可以验证用户输入类型，以便用户仅输入有效值：

* 可以使用工作流运行期间输入的值验证用户输入的字符串和数字类型。
* 也可以使用正则表达式验证字符串类型。
* 此数字类型是一个数值浮点字段，可以使用指定的数值范围进行验证。




 a| 
锁定值
 a| 
您可以锁定查询和枚举类型的值，以防止用户覆盖下拉值并仅允许选择显示的值。



 a| 
标记为必填项
 a| 
您可以将用户输入标记为必填项，以便用户必须输入某些用户输入才能继续执行工作流。



 a| 
分组
 a| 
您可以对相关用户输入进行分组，并为用户输入组提供一个名称。可以在用户输入对话框中展开和折叠这些组。您可以选择默认应展开的组。



 a| 
应用条件
 a| 
通过条件用户输入功能，您可以根据为其他用户输入输入的值设置用户输入的值。例如，在配置 NAS 协议的工作流中，您可以将协议所需的用户输入指定为 NFS ，以启用 "`读 / 写主机列表` " 用户输入。

|===