---
permalink: workflows/concept-how-entity-versioning-works.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, entities, commands, version number, easily, manage, change 
summary: 命令和工作流等 OnCommand Workflow Automation （ WFA ）实体已进行版本控制。您可以使用版本号轻松管理对 WFA 实体所做的更改。 
---
= 实体版本控制的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
命令和工作流等 OnCommand Workflow Automation （ WFA ）实体已进行版本控制。您可以使用版本号轻松管理对 WFA 实体所做的更改。

每个 WFA 实体都包含一个版本号，格式为 `major.minor.revision` 格式—例如 1.1.20 。版本号的每个部分最多可以包含三位数。

在修改 WFA 实体的版本号之前，您必须了解以下规则：

* 版本号不能从当前版本更改为早期版本。
* 版本的每个部分都必须是一个介于 0 到 999 之间的数字。
* 默认情况下，新的 WFA 实体版本为 1.0.0 。
* 在克隆或使用 * 另存为 * 保存实体副本时，实体的版本号会保留下来。
* 一个 WFA 安装中不能存在多个版本的实体。


更新 WFA 实体的版本时，其直接父实体的版本将自动更新。例如，更新 * 创建卷 * 命令的版本将更新 * 创建 NFS 卷 * 工作流，因为 * 创建 NFS 卷 * 工作流是 * 创建卷 * 命令的直接父实体。对版本的自动更新应用如下：

* 修改实体的主要版本将更新其直接父实体的次要版本。
* 修改实体的次要版本将更新其直接父实体的修订版本。
* 修改实体的修订版不会更新其直接父实体版本的任何部分。


下表列出了 WFA 实体及其直接父实体：

[cols="2*"]
|===
| 实体 | 直接父实体 


 a| 
缓存查询
 a| 
* 数据源类型




 a| 
模板
 a| 
* 工作流




 a| 
功能
 a| 
* 工作流
* 模板



NOTE: 如果函数包含特殊或混合大小写字符，则其直接父实体的版本可能不会更新。



 a| 
词典
 a| 
* 模板
* 筛选器
* 缓存查询
* 命令
* 使用脚本方法的数据源类型




 a| 
命令
 a| 
* 工作流




 a| 
筛选器
 a| 
* 查找器
* 工作流




 a| 
查找器
 a| 
* 工作流




 a| 
数据源类型
 a| 
无



 a| 
工作流
 a| 
无

|===
您可以使用版本号的部分或完整版本号在 WFA 中搜索实体。

如果删除父实体，则子实体将被保留，并且其版本不会因删除而更新。



== 版本控制在导入实体时的工作原理

如果您从 Workflow Automation 2.2 之前的版本导入实体，则默认情况下，这些实体的版本将为 1.0.0 。如果导入的实体已存在于 WFA 服务器中，则现有实体将被导入的实体覆盖。

以下是导入期间 WFA 实体可能发生的更改：

* 实体升级
+
这些实体将替换为更高版本。

* 回滚实体
+
这些实体将替换为早期版本。

+

NOTE: 执行实体回滚时，将更新其直接父实体的版本。

* 导入新实体



NOTE: 您不能有选择地从 ` .dar` 文件导入实体。

如果导入了某个实体的更高版本，则会更新其直接父实体的版本。

如果导入的父实体具有多个子实体，则只会对父实体应用对子实体所做的最大更改（主要，次要或修订）。以下示例说明了此规则的工作原理：

* 对于已导入的父实体，如果一个子实体有少许更改，而另一个子实体有修订更改，则此次要更改将应用于父实体。
+
父版本的修订部分将递增。

* 对于导入的父实体，如果一个子实体发生重大更改，而另一个子实体发生轻微更改，则此重大更改将应用于父实体。
+
父版本的次要部分将递增。





== 导入的子实体版本如何影响父版本的示例

请考虑 WFA 中的以下工作流： "`Create Volume and export using NFS - Custom` " 1.0.0 。

此工作流中包含的现有命令如下所示：

* "`创建导出策略 - 自定义` " 1.0.0
* "`Create Volume - Custom` " 1.0.0


要导入的 ` .dar` 文件中包含的命令如下：

* "`创建导出策略 - 自定义` " 1.1.0
* "`Create Volume - Custom` " 2.0.0


导入此 ` .dar` 文件时， "`Create Volume and export using NFS - Custom` " 工作流的次要版本将递增至 1.1.0 。
