---
permalink: workflows/concept-what-a-playground-database-is.html 
sidebar: sidebar 
keywords: playground, database, mysql, include, Workflow, automation, server, installation, add, tables, information, filters, queries, user, input 
summary: 实践数据库是一个 MySQL 数据库，包含在 Workflow Automation （ WFA ）服务器安装中。您可以将表添加到实践数据库中以包含信息，筛选器和 SQL 查询可使用这些信息进行用户输入。 
---
= 什么是实践数据库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
实践数据库是一个 MySQL 数据库，包含在 Workflow Automation （ WFA ）服务器安装中。您可以将表添加到实践数据库中以包含信息，筛选器和 SQL 查询可使用这些信息进行用户输入。

实践数据库是一种无法通过 WFA Web 门户访问的模式。您可以使用 SQLyog ， Toad for MySQL 和 MySQL Workbench 等 MySQL 客户端或命令行界面（ CLI ）访问数据库。

您必须使用以下凭据来访问实践数据库：

* 用户名： WFA
* 密码： Wfa123


通过这些凭据，您可以完全访问实践数据库，并对 WFA MySQL 数据库中定义的其他架构进行只读访问。您可以在实践数据库中创建所需的表。

您可以将用于环境中存储对象的标记或元数据添加到实践数据库中的表中。然后， WFA 筛选器和用户输入查询可以将这些标记或元数据与其他 WFA 缓存表中的信息结合使用。

例如，您可以将实践数据库用于以下使用情形：

* 使用业务单位（ Business Unit ， BU ）名称标记聚合并根据这些标记将卷分配给总线
* 使用 BU 名称标记 vFiler 单元
* 向存储对象添加地理或位置详细信息
* 定义数据库管理员对数据库的访问权限


例如，如果您使用 BU 的名称作为存储对象（例如聚合和 vFiler 单元）的标记，则可以在实践数据库中创建一个包含 BU 名称的表。然后，工作流的筛选器和用户输入查询可以使用此 BU 名称。

以下是实践数据库表示例（ playground.volume_bu ）：

[cols="3*"]
|===
| array_ip | volume_name | 业务单位 


 a| 
10.225.126.23
 a| 
数据 _11
 a| 
营销



 a| 
10.225.126.28
 a| 
arch_11
 a| 
人力资源

|===
下面是一个 SQL 查询示例，您可以使用此示例按 BU 筛选卷：

[listing]
----
SELECT
    vol.name,
    array.ip AS 'array.ip'
FROM
    storage.volume AS vol,
    storage.array AS array,
    playground.volume_bu AS vol_bu
WHERE
    vol.array_id = array.id
    AND array.ip = vol_bu.array_ip
    AND vol.name = vol_bu.volume_name
    AND vol_bu.bu = '{$bu}'
----
* 相关信息 *

https://www.webyog.com/["SQLyog"^]

http://www.mysql.com/products/workbench/["MySQL Workbench"^]

http://www.quest.com/toad-for-mysql/["适用于 MySQL 的 TOAD"^]
